service: market-service

plugins:
  - serverless-esbuild
  - serverless-pseudo-parameters

custom:
  MarketTable:
    name: !Ref MarketTable
    arn: !GetAtt MarketTable.Arn
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  environment:
    MARKET_TABLE_NAME: ${self:custom.MarketTable.name}
  iamRoleStatements:
    - ${file(iam/MarketTableIAM.yml):MarketTableIAM}

resources:
  Resources:
    MarketTable: ${file(resources/MarketTable.yml):MarketTable}

functions:
  postItem:
    handler: src/handlers/postItem.handler
    events:
      - http:
          method: POST
          path: /item
          cors: true
          authorizer: ${self:custom.authorizer}

  getItems:
    handler: src/handlers/getItems.handler
    events:
      - http:
          method: GET
          path: /items
          cors: true
          authorizer: ${self:custom.authorizer}

  getItem:
    handler: src/handlers/getItem.handler
    events:
      - http:
          method: GET
          path: /item/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /item/{id}/bid
          cors: true
          authorizer: ${self:custom.authorizer}

  getItemsBySeller:
    handler: src/handlers/getItemsBySeller.handler
    events:
      - http:
          method: GET
          path: /seller
          cors: true
          authorizer: ${self:custom.authorizer}

  processItems:
    handler: src/handlers/processItems.handler
    events:
      - schedule: rate(1 minute)
